### ISSUE TITLE
Sitemap not updating

### ISSUE THREAD

**Issue by endrehegyi** [cofoundry-cms/Cofoundry.Plugins.SiteMap#3]
Hi I've added the sitemap nuget package to my Cofoundry project.
Navigating to /sitemap.xml shows all the correct adresses for my pages however I have one problem:

The last modified date is the date of when the page was created, modifying this page (i.e. adding additional content to the page via page blocks) does not update this date. 

Is this the intentional way the package should behave or did I miss some implementation? 

This is a problem for me as SERPs can use the sitemap.xml file to know if a site has been updated or not, something that's rather important for blogs.

Thank you.

**Comment by HeyJoel** [comment]
The last modified date is set to the publish date, which at the moment doesn't change if you update a page. At some point in the future you will be able to update the publish date in the UI if you re-publish a resource, but even then what you really need is a last updated date, because the publish date will usually be set for the first time a page/custom entity is published (e.g. a blog publish date).

To fix this we'll need to check to make sure the updated date on a resource is set when it is published in the core Cofoundry project, then we'll need to pull that through and use it here.

Having said that, it is my understanding that search engines ignore these dates anyway (and priority values), specifically google which will decide itself when and how to re-index your site, so I wouldn't worry unduly about it.

**Comment by HeyJoel** [comment]
Fixed, will be released alongside Cofoundry v0.10
